name: Build and Run Service in Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Docker Compose로 서비스 빌드 및 실행
      - name: Build and run services
        run: |
          # GitHub Secret(ENV_FILE_BACKEND)의 내용을 .env.production 파일로 생성합니다.
          echo "${{ secrets.ENV_FILE_BACKEND }}" > ./ts_backend/.env.production

          # docker-compose.yml이 있는 루트 디렉터리로 이동하여 실행
          # 이미지 이름은 docker-compose.yml에 정의된 로컬 이름을 사용합니다.
          docker-compose -f ./docker-compose.yml build
          docker-compose -f ./docker-compose.yml up -d

      # 3. 서비스 동작 확인 (테스트)
      - name: Verify service is running
        run: |
          echo "Waiting for the service to start..."
          sleep 20

          echo "Checking running containers:"
          docker-compose -f ./docker-compose.yml ps

          echo "Testing API endpoint:"
          curl --fail http://localhost:8081/api/auth/health || exit 1
