name: Build and Run on Synology Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    # 이 워크플로우는 self-hosted runner에서만 실행되도록 지정합니다.
    runs-on: self-hosted

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Docker Compose로 서비스 빌드 및 실행
      - name: Build and run services
        run: |
          # GitHub Secret(ENV_FILE_BACKEND)의 내용을 .env.production 파일로 생성합니다.
          echo "${{ secrets.ENV_FILE_BACKEND }}" > ./.env.production

          # 로그 디렉터리가 없을 경우 에러가 발생하므로 미리 생성합니다.
          mkdir -p ./logs

          # Synology DSM 환경에 맞는 'docker compose' (하이픈 없음) 명령어를 사용합니다.
          docker compose build --no-cache
          docker compose up -d

      # 3. 서비스 동작 확인 (테스트)
      - name: Verify service is running
        run: |
          echo "Waiting for the service to start..."
          sleep 40 # 시작 대기 시간을 40초로 늘립니다.

          echo "Checking running containers:"
          docker compose ps

          echo "Testing API endpoint:"
          # 테스트에 실패할 경우, 로그를 출력하고 실패 처리합니다.
          curl --fail http://localhost:8081/api/auth/health || (echo "\n--- Health check failed. Displaying container logs: ---" && docker compose logs && exit 1)
